[WIP] KuCoinのサポート
MtkN1/pybotters pull request #185
Opened 2022-10-07 14:54 UTC by ko0hi

KuCoin（[公式ドキュメント](https://docs.kucoin.com/futures/#general)）の実装をしています！

- [ ] Auth
- [ ] Socket
- [ ] DataStore

KuCoinの[ソケット接続の仕様](https://docs.kucoin.com/futures/#apply-for-connection-token)に対応するために、新たに`DynamicEndpoint`・`DynamicEndpointHosts`というクラスを導入しました。こちらは`WebSocketRunner._run_forever`の最初に呼びだされ、URLの動的解決を行います。この仕様上静的なエンドポイントが存在しないため、`ws_connect`に渡すURLは`kucoin`としました（以下のサンプルが参照ください）。

現状以下ができており、順にストアを作っていこうかと思っています。

- ソケットの接続確認（public/private）
-  REST APIの認証確認

```python
class WebSocketRunner:

    ... 

  async def _run_forever(

       ...

    ) -> None:
        if url in DynamicEndpointHosts.items:
            url = await DynamicEndpointHosts.items[url](url, session)

        ...

class DynamicEndpoint:
    @staticmethod
    async def kucoin(url: str, session: aiohttp.ClientSession):
        api_keys = session.__dict__["_apis"]
        if "kucoin" in api_keys:
            # public and private
            from pybotters.auth import Auth
            resp = await session.post(
                "https://api-futures.kucoin.com/api/v1/bullet-private", auth=Auth
            )
        else:
            # public only
            resp = await session.post(
                "https://api-futures.kucoin.com/api/v1/bullet-public"
            )
        data = (await resp.json())["data"]
        token = data["token"]
        server = data["instanceServers"][0]
        endpoint = server['endpoint']
        id = str(uuid.uuid4())
        host = aiohttp.typedefs.URL(endpoint).host
        HeartbeatHosts.items[host] = Heartbeat.kucoin
        return f"{endpoint}?token={token}&acceptUserMessage=true&connectId={id}"

class DynamicEndpointHosts:
    items = {
        "kucoin": DynamicEndpoint.kucoin
    }

```

### サンプルコード
```python
import pybotters
import uuid

with pybotters.Client(base_url="https://api-futures.kucoin.com") as client:
    # socket 接続
    # kucoinのソケットエンドポイントは動的に決まるので、"kucoin"と渡すことでエンドポイントの解決は内部で行なれる
    await client.ws_connect(
        "kucoin",
        send_json=[
            {
                "id": str(uuid.uuid4()),
                "type": "subscribe",
                "topic": "/contractMarket/tickerV2:XBTUSDM",
                "response": True
            },
    
            {
                "id": str(uuid.uuid4()),
                "type": "subscribe",
                "topic": "/contractMarket/tradeOrders:XBTUSDM",
                "privateChannel": True,
                "response": True
            }
        ],
    )

    # get tick
    await client.get("/api/v1/ticker", params=dict(symbol="XBTUSDTM"))
    
    # order
    await client.post(
        "/api/v1/orders",
        data=dict(
            clientOid=str(uuid.uuid4()),
            side="buy",
            symbol="XBTUSDTM",
            type="limit",
            leverage="1",
            price="19200",
            size=1
        ),
    )
```

2022-10-08 00:53 UTC, MtkN1 commented
PRありがとうございます！ KuCoin 対応ですね 🚀
仕様・設計等何か気付いたらコメントします。

2022-10-12 15:54 UTC, ko0hi commented
kline取得

```python
async def sample1():
    async with pybotters.Client() as client:
        store = pybotters.KucoinDataStore()

        await store.initialize(client.get("https://api.kucoin.com/api/v1/market/candles?type=1min&symbol=BTC-USDT"))
        await client.ws_connect(
            "kucoinspot",
            send_json=[
                {
                    "id": str(uuid.uuid4()),
                    "type": "subscribe",
                    "topic": "/market/candles:BTC-USDT_1min",
                    "response": True
                },
                {
                    "id": str(uuid.uuid4()),
                    "type": "subscribe",
                    "topic": "/market/candles:BTC-USDT_3min",
                    "response": True
                },
            ],
            hdlr_json=store.onmessage
        )


        while True:
            rich.print(
                [
                    # 未確定足
                    store.kline.latest("BTC-USDT", "1min"),
                    store.kline.latest("BTC-USDT", "3min"),
                    # 確定足　
                    store.kline.find({"symbol": "BTC-USDT", "interval": "1min"})[-2:],
                    store.kline.find({"symbol": "BTC-USDT", "interval": "3min"})[-2:]
                ]
            )
            await asyncio.sleep(1)
```

約定監視
```python
async def sample2():
    async with pybotters.Client() as client:
        store = pybotters.KucoinDataStore()
        await client.ws_connect(
            "kucoinfuture",
            send_json=[
                {
                    "id": str(uuid.uuid4()),
                    "type": "subscribe",
                    "topic": "/contractMarket/execution:XBTUSDTM",
                    "response": True
                }
            ],
            hdlr_json=store.onmessage
        )

        with store.execution.watch() as stream:
            async for msg in stream:
                rich.print(msg)
```

注文
```python
async def sample3():
    # 注文
    async with pybotters.Client({
        "kucoinfuture": [
            "XXXXXXX",
            "XXXXXXX",
            "XXXXXXX"
        ]
    }) as client:
        store = pybotters.KucoinDataStore()
        await client.ws_connect(
            "kucoinfuture",
            send_json=[
                {
                    "id": str(uuid.uuid4()),
                    "type": "subscribe",
                    "topic": "/contractMarket/tradeOrders",
                    "privateChannel": True,
                    "response": True
                },
            ],
            hdlr_json=store.onmessage
        )
    
        await client.post(
            "https://api-futures.kucoin.com/api/v1/orders",
            data=dict(
                clientOid=str(uuid.uuid4()),
                side="buy",
                symbol="XBTUSDTM",
                type="limit",
                price="18000",
                leverage=1,
                size=1  # lot = 0.001 BTC
            ),
        )
    
        await asyncio.sleep(1)
    
        rich.print(store.orders.find())
    
        await client.delete("https://api-futures.kucoin.com/api/v1/orders")
    
        await asyncio.sleep(1)
    
        rich.print(store.orders.find())
```

2022-10-13 15:41 UTC, MtkN1 commented
ありがとうございます！ 後日レビューさせて頂きます。

2022-10-18 16:42 UTC, MtkN1 requested changes
お待たせしてしまいすみません！
REST / WebSocket 認証の変更部分については確認しました。

WebSocket エンドポイントの動的解決クラス `DynamicEndpoint` ですが、動的解決の機能は大変便利なのですが pybotters としての現在の思想上このような高レベルな機能を Client に組み込むことは出来ません。
似たようなトークン取得形式で WS に接続する GMO と Binance についてはユーザー自身にトークン取得を任せています。
https://github.com/MtkN1/pybotters/releases/tag/v0.4.0
https://github.com/MtkN1/pybotters/releases/tag/v0.10.0

`await client.ws_connect("kucoinfuture")` のような形で WS 接続するできる便利ですが一般性 (取引所ドキュメントに記載されているかどうか) がなく『pybotters KuCoin ラッパー』的な役割だと思っています。
Client クラスからなる認証ロジックの簡潔性を保つためにも、暗黙のリクエストや取引所のエンドポイントのハードコードは出来るだけ避けて、低レベルな設計に収めておきたいです。

***ですので、ws.py の変更は Heartbeat の追加のみにして頂けたらと思います。***

そうは言っても実際 bot をコーディングする際はあるに越したことはない機能なので utils 的な感じで違うモジュールとして残す良い方法はないかな思っています...🤔

2022-10-18 16:46 UTC, MtkN1 commented
- [x] ✅ REST 認証
- [ ] ⚠️ WS 認証
- [ ] ⌛ DataStore

2022-10-18 19:47 UTC, ko0hi commented
レビューありがとうございます。

> ですので、ws.py の変更は Heartbeat の追加のみにして頂けたらと思います。


こちら承知しました。そのようにコードを変更しますね。

> そうは言っても実際 bot をコーディングする際はあるに越したことはない機能なので utils 的な感じで違うモジュールとして残す良い方法はないかな思っています...🤔

GMOのようにstoreのinitialize methodに `https://api-futures.kucoin.com/api/v1/bullet-private`を渡すことで、`initialize`内でendpointの動的解決を行なって、`KucoinDataStore.endpoint`からアクセスできる、というのはいかがでしょうか。以下イメージです。

```python
async def main():
    async with pybotters.Client(base_url="https://api-futures.kucoin.com") as client:

        store = pybotters.KucoinDataStore()

        await store.initialize(
            # 内部で動的解決を行う
            client.post("/api/v1/bullet-private")
        )

        await client.ws_connect(
            store.endpoint,
            send_json=[
                ...
            ],
            onmessage=store.onmessage
        )
```

上の実装で一点気になるのは、`models/kucoin/KucoinDataStore.initialize`の中から`ws/HertbeatHosts.items`をいじることになる点です（今は同一モジュール内の`DynamicEndpoint`で行なっている：https://github.com/MtkN1/pybotters/pull/185/files#diff-49d1f84f1def843a2a01d170b4691c7b5cab0f8856a32dfbea84807806821609R635）。

いかがでしょうか。

2022-10-19 13:40 UTC, MtkN1 commented
> GMOのようにstoreのinitialize methodに `https://api-futures.kucoin.com/api/v1/bullet-private`を渡すことで、`initialize`内でendpointの動的解決を行なって、`KucoinDataStore.endpoint`からアクセスできる、というのはいかがでしょうか。以下イメージです。

DataStore は取引所個別の抽象化を行っているのでありですね！
initialize に渡したら token 入りの endpoint をインスタンス変数に格納する実装は OK です。

> 上の実装で一点気になるのは、`models/kucoin/KucoinDataStore.initialize`の中から`ws/HertbeatHosts.items`をいじることになる点です（今は同一モジュール内の`DynamicEndpoint`で行なっている：[https://github.com/ko0hi/pybotters/blob/feature/kucoin/pybotters/ws.py#L635）。](https://github.com/ko0hi/pybotters/blob/feature/kucoin/pybotters/ws.py#L635%EF%BC%89%E3%80%82)

うーん、DataStore からの HeartbeatHosts.items の動的追加もあまり好ましくないと思っています。
DataStore と Client からなるクラスの間にはコールバックとしての関係以外、出来るだけ依存性を持たせたくありません。(現状一部依存性があるは課題です)
やるとするとどちらかにしたいです。

- 現状のエンドポイント `wss://ws-api.kucoin.com/endpoint` をハードコードしてしまう
- 敢えて PING メッセージを送信しない
  - 実は他の取引所でもそうなんですが、`await client.ws_connect(..., heartbeat=10.0)` と **PING フレームのハートビート** を設定すると取引所指定の PING メッセージのハートビートを送らなくても多くの取引所は切断されません。 KuCoin に関しても切断されないっぽいです（確認中）

2022-10-20 16:41 UTC, MtkN1 commented
あ、`heartbeat=10.0` はデフォルト引数として設定しています。 なので事実上切断はされないので警告はなしにしましょう。
取り敢えず PING メッセージのホスト仕様としては、`wss://ws-api.kucoin.com/endpoint` のハードコードでお願いします！

2022-10-21 01:24 UTC, ko0hi commented
- [ ] `DynamicEndpoint`周りのコードを `ws.py`から削除
- [ ] エンドポイントの動的解決を initializeメソッド内に実装
- [ ] `wss://ws-api.kucoin.com/endpoint`を `HeartbeatHosts.items`にハードコード

の修正を入れていきます！

2022-10-21 13:58 UTC, ko0hi commented
修正完了しました。

orderbookにバグがあったのと `sorted`メソッドを実装し忘れていたので、そちらも追加で入れています。

以下修正後のサンプルコードです。お手隙の際レビューよろしくお願いします。

```python
import asyncio
import pybotters
import uuid
import rich


async def sample1():
    # kline取得
    async with pybotters.Client(base_url="https://api.kucoin.com") as client:
        store = pybotters.KucoinDataStore()

        await store.initialize(
            client.get("/api/v1/market/candles?type=1min&symbol=BTC-USDT"),
            client.post("/api/v1/bullet-public"),
        )
        await client.ws_connect(
            store.endpoint,
            send_json=[
                {
                    "id": str(uuid.uuid4()),
                    "type": "subscribe",
                    "topic": "/market/candles:BTC-USDT_1min",
                    "response": True,
                },
                {
                    "id": str(uuid.uuid4()),
                    "type": "subscribe",
                    "topic": "/market/candles:BTC-USDT_3min",
                    "response": True,
                },
            ],
            hdlr_json=store.onmessage,
        )

        while True:
            rich.print(
                [
                    # 未確定足
                    store.kline.latest("BTC-USDT", "1min"),
                    store.kline.latest("BTC-USDT", "3min"),
                    # 確定足
                    store.kline.find({"symbol": "BTC-USDT", "interval": "1min"})[-2:],
                    store.kline.find({"symbol": "BTC-USDT", "interval": "3min"})[-2:],
                ]
            )
            await asyncio.sleep(1)


async def sample2():
    # 約定監視
    async with pybotters.Client(base_url="https://api-futures.kucoin.com") as client:
        store = pybotters.KucoinDataStore()
        await store.initialize(client.post("/api/v1/bullet-public"))
        await client.ws_connect(
            store.endpoint,
            send_json=[
                {
                    "id": str(uuid.uuid4()),
                    "type": "subscribe",
                    "topic": "/contractMarket/execution:XBTUSDTM",
                    "response": True,
                }
            ],
            hdlr_json=store.onmessage,
        )

        with store.execution.watch() as stream:
            async for msg in stream:
                rich.print(msg)


async def sample3():
    # 板監視
    async with pybotters.Client(base_url="https://api-futures.kucoin.com") as client:
        store = pybotters.KucoinDataStore()
        await store.initialize(client.post("/api/v1/bullet-public"))
        await client.ws_connect(
            store.endpoint,
            send_json=[
                {
                    "id": str(uuid.uuid4()),
                    "type": "subscribe",
                    "topic": "/contractMarket/level2Depth5:XBTUSDTM",
                    "response": True,
                }
            ],
            hdlr_json=store.onmessage,
        )

        while True:
            await store.orderbook5.wait()
            rich.print(store.orderbook5.sorted())


async def sample4():
    # 注文
    async with pybotters.Client(
        base_url="https://api-futures.kucoin.com",
        apis={
            "kucoinfuture": [
                "YOUR_API_KEY",
                "YOUR_SECRET_KEY",
                "YOUR_PASSPHRASE",
            ]
        },
    ) as client:
        store = pybotters.KucoinDataStore()
        await store.initialize(client.post("/api/v1/bullet-private"))
        await client.ws_connect(
            store.endpoint,
            send_json=[
                {
                    "id": str(uuid.uuid4()),
                    "type": "subscribe",
                    "topic": "/contractMarket/tradeOrders",
                    "privateChannel": True,
                    "response": True,
                },
            ],
            hdlr_json=store.onmessage,
        )

        await client.post(
            "/api/v1/orders",
            data=dict(
                clientOid=str(uuid.uuid4()),
                side="buy",
                symbol="XBTUSDTM",
                type="limit",
                price="18000",
                leverage=1,
                size=1,
            ),
        )

        await asyncio.sleep(1)

        rich.print(store.orders.find())

        await client.delete("/api/v1/orders")

        await asyncio.sleep(1)

        rich.print(store.orders.find())

```

2022-10-26 13:11 UTC, MtkN1 approved these changes
確認致しました！
ストアも期待される動作をしていると思われます。

2点こちらで修正しました。

1. クラス名を `KucoinDataStore` -> `KuCoinDataStore` に変更しました https://github.com/MtkN1/pybotters/pull/185/commits/9cdcfdbfd53096fa87dc3b2db4c5f97d0e73e6b0

```diff
diff --git a/pybotters/models/kucoin.py b/pybotters/models/kucoin.py
index d9a1024..b7897d7 100644
--- a/pybotters/models/kucoin.py
+++ b/pybotters/models/kucoin.py
@@ -18,13 +18,13 @@ def _symbol_from_msg(msg):
     return msg["topic"].split(":")[-1]
 
 
-class KucoinDataStore(DataStoreManager):
+class KuCoinDataStore(DataStoreManager):
     """
     Kucoinのデータストアマネージャー
     """
 
     def __init__(self, *args, **kwargs):
-        super(KucoinDataStore, self).__init__(*args, **kwargs)
+        super(KuCoinDataStore, self).__init__(*args, **kwargs)
         self._endpoint = None
 
     def _init(self) -> None:
```

2. 将来的にストアは認証系のモジュールから分離する予定なので、`HeartbeatHosts` の ImportError 例外をパスするようにしました。  https://github.com/MtkN1/pybotters/pull/185/commits/93409319160dafccb3cd9f6f5aeb0421caf1f9f6

```diff
diff --git a/pybotters/models/kucoin.py b/pybotters/models/kucoin.py
index 18cdf23..d9a1024 100644
--- a/pybotters/models/kucoin.py
+++ b/pybotters/models/kucoin.py
@@ -245,6 +245,7 @@ class KucoinDataStore(DataStoreManager):
         id = str(uuid.uuid4())
         endpoint, host = None, None
 
+        try:
             from pybotters.ws import HeartbeatHosts
 
             for s in servers:
@@ -253,6 +254,11 @@ class KucoinDataStore(DataStoreManager):
                 if host in HeartbeatHosts.items:
                     endpoint = s["endpoint"]
                     break
+        except ImportError as e:
+            logger.warning(
+                "KuCoinDataStore cannot use 'HeartbeatHosts' "
+                f"({e.__class__.__name__}: {e})"
+            )
         # HeartbeatHostsに登録してあるエンドポイントがなかった場合、一番最初のものを使う
         if endpoint is None:
             endpoint = servers[0]["endpoint"]
```

他に問題がなければ Merge 致します。

2022-10-27 00:32 UTC, ko0hi commented
確認修正ありがとうございます。

一点気になっているのは、SpotとFutureで同じStoreManagerを使い回す実装になっている点です。
ドキュメントを見る限り両者で差分がなかったためにこのようにしたのですが、片方でしか使わないDataStoreというのが存在します（例えば `IndexPrice`は対応チャンネルはFutureでのみ使われます）。

#188 にならって、`KuCoinDataStoreBase` ・ `KuCoinSpotDataStore`・`KuCoinFuturesDataStore` （Future**s**でいいですよね？）というように抽象クラスを用意した方が（今更ながら）綺麗な実装かなと思っています。

まちゅけんさんの再レビューの手間がかかることになりますが、このような修正はいかがでしょうか？

2022-10-29 04:13 UTC, MtkN1 commented
クラスは1つのままで行きましょう！

KuCoin API を試して考えた結果としては

- Spot / Futures の WebSocket エンドポイントは現状どちらも `wss://ws-api.kucoin.com/endpoint` である
- Spot / Futures の `POST https://{api|api-futures}.kucoin.com/api/v1/bullet-public` から取得したトークンでそれぞれ WebSocket に繋げても、トークンに関係なくどちらでも Spot / Futures のトピックを購読可能である
  - 恐らく KuCoin 側は1つの WebSocket サーバーで実装しているので断片化の可能性は低い
- なので WebSocket エンドポイント1つを DataStoreManager とし、そこから配信される各トピックを DataStore として定義する、というこれまでの方針で問題なさそう
  - 他の Spot / Futures (Perpetual) 共通エンドポイントの取引所でも現物には存在しないデータのストアが定義されている

といった感じです。

ただ個人的に好きなのはトピック名に倣ってプロパティを `store.contractmarket_tickerv2` のように冗長的に定義するのもありだと思うんですがどうでしょう？ 公式ドキュメントに照らし合わせながら「そのストアは Futures のやつか」と使う時分かりやすい気がしてます。 (現状でも docstrings に書いて頂いてるんですが)

pe さんが「クラス別にしないならこの提案はありかも」と考えるのであれば修正して頂いていいですし、特にいいなら現状機能としては問題ないのでこのままマージでも大丈夫です。(私で実装しているストアでもデザインが結構断片化している ... ので必須ではないという意です)

2022-10-29 12:34 UTC, ko0hi commented
確認ありがとうございます。現行の実装で行くのも承知しました。理由についても疑問点ありません。

> ただ個人的に好きなのはトピック名に倣ってプロパティを store.contractmarket_tickerv2 のように冗長的に定義するのもありだと思うんですがどうでしょう？

こちら同意なんですが、SpotとFutureを使いまわしてる都合上どちらに合わせるかという悩みがでたので（例えば、tickerはspotなら `market_ticker`、futuresなら `contractmarket_tickerv2`）、よろしければこのままでいかせてもらえたらと思います。

自分の方で現時点で気になる点はないのでmergeしていただけるのであれば非常に嬉しいです！

2022-10-29 12:41 UTC, MtkN1 commented
ではマージ致します！
素晴らしい機能の Contribute ありがとうございます & 議論お疲れでした ☕🍰

2022-10-29 12:41 UTC, merged