Bugfix/kucoin position store
MtkN1/pybotters pull request #198
Opened 2022-11-15 15:21 UTC by ko0hi

修正パッチ #197 

- _onmessageのロジックを更新
- 合わせて_onresponseを更新

2022-11-15 16:03 UTC, MtkN1 commented
PR ありがとうございます！
こちらでも Position 配信データをチェックしてみます。

2022-11-16 06:44 UTC, ko0hi commented
よろしくお願いします！

一応補足ですが、元のコードのこの部分もそもそも間違っていました（currentQty < 0でショートポジション・currentQty > 0でロングポジションなので、ロングポジションの時にしかifブロックに入れなかった）。
```python
if d.get("currentQty", 1) > 0
   self._update([d])
```

2022-11-16 09:23 UTC, MtkN1 reviewed
コード確認しました！
1 件コメント追加しました。

あと PR とは関係なくて申し訳ないんですが KuCoin の Sandbox [^1] って機能してますかね？
ちょっと KuCoin に資産が入っておらず、正直前回 PR も資産ない状態で試せる範囲で確認していました。
今回はポジションの具体的な修正なので流石に確認するかと思い、ドキュメントみると testnet 的な Sandbox があったので試そうとしたんですが、注文してもポジションが増える様子がないです。 (これは Web UI で行っている)
Sandbox が正常なものであれば pybotters のホストにも追加しようかなと思ったのですが、 KuCoin 全然分からずもし知っていたら or Sandbox 触れたら教えて頂きたく 🙏

[^1]: https://docs.kucoin.com/futures/#sandbox

2022-11-16 09:23 UTC, MtkN1 commented on pybotters/models/kucoin.py
> +                self._insert([{"side": "BUY" if d["currentQty"] > 0 else "SELL", **d}])
KuCoin のレスポンスを教えて頂きたいのですが、ノーポジションの時は引数 _data_ は空のリストが返ってくる認識で大丈夫ですか？
(3 項演算子で _currentQty == 0_ だと _"side": "SELL"_ になる為)

2022-11-16 12:28 UTC, ko0hi commented on pybotters/models/kucoin.py
> +                self._insert([{"side": "BUY" if d["currentQty"] > 0 else "SELL", **d}])
はいそうです。ノーポジションの時は dataが空のリストになってます。

l.668 の `if d["isOpen"]` はいらないかもとは思ったのですが、念の為二重でopenのポジションだけ挿入しています。

2022-11-16 12:35 UTC, ko0hi commented
３点補足です

1. "(3 項演算子で currentQty == 0 だと "side": "SELL" になる為)"について

_onmessage内でも以下のように三項演算子で定義してるのですが、こちら自分で観測した限り `d["isOpen"] = True`の時 `d["currentQty"] != 0`・ `d["isOpen"] = False`の時`d["currentQty"] = 0`となっているので問題ないように思えます。
ただ念の為 `assert d["currentQty"] != 0` など入れることも可能ですがいかがでしょうか？

```python
if reason == "positionChange":
    if d["isOpen"]:
        d["side"] = "BUY" if d["currentQty"] > 0 else "SELL"
        self._update([d])
    else:
        self._delete([d])
```
2. _deleteの仕方について

#193 と同じ話なのですが、KuCoinの実装でもポジション決済時に削除のみを行なって、poisition sizeを0で更新→削除となっていません。

```python
if reason == "positionChange":
    d["side"] = "BUY" if d["currentQty"] > 0 else "SELL"
    if d["isOpen"]:
        self._update([d])
    else:
        self._update([d])
        self._delete([d])
```

とするとposition sizeを0で更新→削除、という処理になるのですがこのように変更しますか？


3. sandboxについて

こちら使ったことはありませんでした。試してみたのですがそもそもテスト環境へのサインアップができず検証できずという状況です。

2022-11-16 15:32 UTC, MtkN1 commented
> 1. "(3 項演算子で currentQty == 0 だと "side": "SELL" になる為)"について

レスポンスの内容了解しました。 そうですね、念のためアサーションだけ追加お願いします！

> 2. _deleteの仕方について

他の Issue も確認して頂いてありがとうございます！
https://github.com/MtkN1/pybotters/issues/193#issuecomment-1317195028 を先に書いたのですがまだ対応方法を検討中なので現状のコードのままでお願いします。

> 3. sandboxについて

[ツイート](https://twitter.com/MtkN1XBt/status/1592835150324199424) の方でもリプライ & 試して頂いてありがとうございます。 
認証メールは 3 回ぐらい Resend を待っていたら届いて登録できましたw
正直 Sandbox 全く分からないし、そもそも取引エンジンがおかしい気がするのでやめておきます。

KuCoin の確認については取り敢えずコーディングの確認のみで対応致します！ (再三自分に言い聞かせてますが、単体テストできるようにしないと ...)

2022-11-16 15:34 UTC, MtkN1 requested changes

2022-11-16 15:34 UTC, MtkN1 commented on pybotters/models/kucoin.py
> +                self._insert([{"side": "BUY" if d["currentQty"] > 0 else "SELL", **d}])
アサーション追加お願いします

2022-11-16 16:48 UTC, MtkN1 approved these changes
LGTM

2022-11-21 07:59 UTC, merged