Bybit の Derivatives v3 API に対応する
MtkN1/pybotters pull request #219
Opened 2023-01-10 19:03 UTC by cococig

#184 の修正
* WebSocketでBybitのprivate channelの認証が通るようにしました
  * 手元のDerivatives V3 Contract API Testnetで動作を確認しました
* 合わせてtest_ws.pyにBybit用のテストケースを追加しました
* REST APIでの認証については現状のままでもDerivatives V3 Contract APIでは問題なく動作しているため、変更を加えていません

2023-01-11 17:39 UTC, MtkN1 commented
PR ありがとうございます！

REST API が現状の認証で通るというのは認識してませんでした。 であれば WebSocket の変更だけでよさそうですね。
こちらでも動作確認してみます。

2023-01-16 11:34 UTC, MtkN1 requested changes
確認致しました！

✅ Derivatives v3 Contract API に関しては動作確認しました。

しかしながら実際にリクエストして検証してると一部問題点があります。

## 問題点

1. Derivatives v3 Contract API は認証が通るが Derivatives v3 Unifired Margin API は認証は通らない

例えば Unifired Margin の `https://api.bybit.com/unified/v3/private/account/wallet/balance` は認証が通らないようです。

👉 これ自体は対応不要で、この PR は Derivatives v3 Contract API のみ暫定対応する要件の PR に変更させてください。 Unifired Margin のテストは USD デリバティブアカウントにアップグレードが必要ですし、問題点が色々とみえたのでより包括的に v3 API に対応できるような実装を自分の方で対応したいと思います。

2. WebSocket の認証メッセージ送信が Bybit の他の契約タイプの処理に影響を与えており、例えば Invserse 契約でも認証メッセージが送信されてしまいサーバー側に切断される

```py
# 確認コード
async def main():
    async with pybotters.Client() as client:
        ws = await client.ws_connect(
            "wss://stream.bybit.com/realtime",
            send_json={"op": "subscribe", "args": ["wallet"]},
        )
        await ws
```

main ブランチであれば `{'success': True, 'ret_msg': '', 'conn_id': '182b5330-c603-47dd-b59f-4cde5cb3da8c', 'request': {'op': 'subscribe', 'args': ['wallet']}}` と print されますが PR ブランチであると何も出力されなくなります。

👉 一先ずバグを無くすため WS エンドポイントパスを `/contract/private/v3` から始まる場合認証を送るよう suggestion のように修正お願いしてよろしいでしょうか？

2023-01-16 11:34 UTC, MtkN1 commented on pybotters/ws.py
> +        key: str = ws._response._session.__dict__["_apis"][
```suggestion
    async def bybit(ws: aiohttp.ClientWebSocketResponse):
        if not ws._response.url.path.startswith("/contract/private/v3"):
            return

        key: str = ws._response._session.__dict__["_apis"][
```

2023-01-16 13:32 UTC, cococig commented on pybotters/ws.py
> +        key: str = ws._response._session.__dict__["_apis"][
なるほど、Unified Margin APIでは動作が異なるのは盲点でした。確認いただきありがとうございます。
SuggestionをCommitさせていただきました。

2023-01-16 23:57 UTC, MtkN1 approved these changes
LGTM 👍 

暫定対応として Merge させて頂きます。 Contribute ありがとうございました！

2023-01-17 00:31 UTC, merged