bitbank datastore 追加
MtkN1/pybotters pull request #68
Opened 2021-07-09 14:47 UTC by Osaifu-Crypto

# 内容
- bitbank datastore の追加
- public websocketのtransactions, depthに対応
- Heartbeatで15秒ごとに"2"を送信
- FTXのデータストアを流用して作成
- （参考）bitbankのwebsocketドキュメント
https://github.com/bitbankinc/bitbank-api-docs/blob/master/public-stream_JP.md

2021-07-10 17:07 UTC, MtkN1 requested changes
コードをテストしました。
pybottersの中身を理解して頂きそれに沿った書き方をしてくださりありがとうございます。
数点ご確認と修正お願いします。

## (特記)Depth ストアのデータ型について

バグがありまして、item[0]は価格データですが、BTC以外の銘柄XRPなどは小数点のデータも入ってくる為ValueErrorとなってしまいます。
また現在pybottersが取っている方針として ** **文字列型の数値データ** ** が送られてくる場合、文字列型のままデータとして保管するという実装を行っています。 そうしている理由としては、

- 取引所のAPIドキュメントと照らし合わると暗黙的に型変換をしている事になる
- ユーザーが文字列型のままDecimalモジュールで計算したい場合もある
- (本当の理由) float型の方が利便性が高いが特にBybit,Binace等APIは文字列型の数値が多すぎて個別に変換掛けるのが面倒なので全データストア一律そうしている

今後方針は変更する可能性もあるかもしれませんが、現状は提案コードにお願いします。

以下のコードでテストしました。

```python
async def main():
    async with pybotters.Client() as client:
        store = pybotters.bitbankDataStore()
        wstask = await client.ws_connect(
            'wss://stream.bitbank.cc/socket.io/?EIO=3&transport=websocket',
            send_str=[
                # '42["join-room","ticker_xrp_jpy"]',
                '42["join-room","transactions_xrp_jpy"]',
                '42["join-room","depth_whole_xrp_jpy"]',
                '42["join-room","depth_diff_xrp_jpy"]',
            ],
            hdlr_str=store.onmessage,
        )
        # await wstask
        while True:
            # await store.transactions.wait()
            # pybotters.print(store.transactions.find()[-1])
            await store.depth.wait()
            pybotters.print({k:v[:6] for k, v in store.depth.sorted().items()})
```

2021-07-10 17:09 UTC, MtkN1 commented
(余談)
Draftプルリクエストをお願いしましたが、これはコントリビューターの方が ""こういったPRを提出するけど完全じゃないので細かい箇所はまだ変更するかも"" というような表現の機能でした。(今回は実装終わってPR頂いていたのでDraftではありませんでしたね)

2021-07-11 03:45 UTC, Osaifu-Crypto commented on pybotters/models/bitbank.py
> +                if item[1]:
まちゅけんさん、ご丁寧にデータ型の説明していただきありがとうございました。
pybottersのDataStore仕様について理解できました。

たしかにpriceをintにしてしまうとXRPなどでエラーになってしまいますね。
BTCでしか回していなかったため気づかなかったです。

仕様については、取引所ごとに数値か文字列で返すか違うので、
DataStoreでは個別に対応せず、レスポンスそのものを格納するということですね。

公式の仕様通りデータを格納し、そのあとの処理はユーザーに任せたほうが、混乱は少なそうです。

ご指摘いただいたとおり、型変換をやめて、文字列で```!='0'```とするように修正しました。

2021-07-11 03:47 UTC, Osaifu-Crypto commented on pybotters/models/bitbank.py
> +class bitbankDataStore(DataStoreInterface):
確かに固有名詞だと命名規約との整合性は取れないですね。
ただ固有名詞の場合は、固有名詞を優先したほうがわかりやすいですね。

2021-07-11 03:48 UTC, Osaifu-Crypto commented on pybotters/models/bitbank.py
> +    def _onmessage(self, msg: Any, ws: ClientWebSocketResponse) -> None:
str型に変更しました。

2021-07-11 09:06 UTC, MtkN1 commented
@Osaifu-Crypto 修正ありがとうございました！
ちなみに eb067b4b76080df978e554d77b69d2730f3e4025 でスペースの自動整形して頂いていますが、pybottersが選定しているフォーマッター(black)とリンター(flake8)をかける事は可能でしょうか？
先ほどWikiにやり方を記載しました。 https://github.com/MtkN1/pybotters/wiki/Contributing#formatter-linter

難しそうであれば本PRはマージしてその後こちらで行いますが、いかがでしょうか？

2021-07-11 09:06 UTC, MtkN1 approved these changes

2021-07-11 09:17 UTC, Osaifu-Crypto commented
> @Osaifu-Crypto 修正ありがとうございました！
> ちなみに [eb067b4](https://github.com/MtkN1/pybotters/commit/eb067b4b76080df978e554d77b69d2730f3e4025) でスペースの自動整形して頂いていますが、pybottersが選定しているフォーマッター(black)とリンター(flake8)をかける事は可能でしょうか？
> 先ほどWikiにやり方を記載しました。 https://github.com/MtkN1/pybotters/wiki/Contributing#formatter-linter
> 
> 難しそうであれば本PRはマージしてその後こちらで行いますが、いかがでしょうか？

2021-07-11 09:23 UTC, Osaifu-Crypto commented
> @Osaifu-Crypto 修正ありがとうございました！
> ちなみに [eb067b4](https://github.com/MtkN1/pybotters/commit/eb067b4b76080df978e554d77b69d2730f3e4025) でスペースの自動整形して頂いていますが、pybottersが選定しているフォーマッター(black)とリンター(flake8)をかける事は可能でしょうか？
> 先ほどWikiにやり方を記載しました。 https://github.com/MtkN1/pybotters/wiki/Contributing#formatter-linter
> 
> 難しそうであれば本PRはマージしてその後こちらで行いますが、いかがでしょうか？

フォーマッターのやり方を記載していただきありがとうございます。
手順に従ってできると思いますので、やってみます。

それと先程Close wih commentボタンを誤って押してしまいましたため、Reopenしました。失礼しました。

2021-07-11 09:28 UTC, MtkN1 commented
プルリクは何度でもオープン・クローズできるので問題ないですよ～。コメントの真横にあるので仕事でもまたに間違えておします😅

2021-07-11 11:33 UTC, Osaifu-Crypto commented
> プルリクは何度でもオープン・クローズできるので問題ないですよ～。コメントの真横にあるので本業でもまたに間違えておします

最初、closeが取り消せないのかと思いすごい焦りました（笑）
確かに間違えやすいですね。

black, flake8の修正追加しました。

2021-07-11 14:11 UTC, MtkN1 commented
LGTM👍
マージさせて頂きます。ありがとうございました！

2021-07-11 14:12 UTC, merged